import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import 'locale_state.dart';

class AppStrings {
  static const _en = <String, String>{
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.share': 'Share',
    'common.update': 'Update',
    'common.retry': 'Retry',
    'common.undo': 'Undo',
    'common.required': 'Required',
    'common.toggle_password': 'Show or hide password',
    'common.error': 'Error',
    'common.loading': 'Loading…',
    'nav.home': 'Home',
    'nav.my_reports': 'My Reports',
    'nav.profile': 'Profile',
    'nav.report': 'Report',
    'app.exit_title': 'Leave app',
    'app.exit_message': 'Are you sure you want to leave?',
    'app.yes': 'Yes',
    'app.no': 'No',
    'login.welcome_back': 'Welcome Back',
    'login.subtitle': 'Sign in to continue reporting',
    'login.identifier_label': 'PHONE NUMBER',
    'login.identifier_hint': 'Start with 077, 078, or 079',
    'login.password_label': 'PASSWORD',
    'login.password_hint': 'Your password',
    'login.sign_in': 'Sign In',
    'login.no_account': "Don't have an account? ",
    'login.sign_up_link': 'Sign Up',
    'login.invalid_phone': 'Phone must start with 077, 078, or 079',
    'login.enter_phone': 'Enter your phone number',
    'login.phone_not_registered': 'Incorrect Phone Number!',
    'login.wrong_password': 'Incorrect password',
    'ar.phone_number': 'رقم الهاتف',
    'ar.password': 'كلمة المرور',
    'ar.first_name': 'الاسم الأول',
    'ar.last_name': 'اسم العائلة',
    'ar.photo': 'صورة',
    'ar.problem_type': 'نوع المشكلة',
    'ar.description': 'الوصف',
    'ar.location': 'الموقع',
    'register.create_account': 'Create Account',
    'register.subtitle': 'Join thousands reporting civic issues',
    'register.phone_label': 'PHONE NUMBER',
    'register.phone_hint': 'Start with 077, 078, or 079',
    'register.first_name': 'FIRST NAME',
    'register.first_hint': 'First',
    'register.last_name': 'LAST NAME',
    'register.last_hint': 'Last',
    'register.password': 'PASSWORD',
    'register.password_hint': 'Create a password',
    'register.password_min': 'Min 6 characters',
    'register.sign_up': 'Sign Up',
    'register.have_account': 'Already have an account? ',
    'register.sign_in_link': 'Sign In',
    'home.welcome': 'Welcome',
    'home.stat_total': 'Total',
    'home.stat_resolved': 'Resolved',
    'home.stat_active': 'Active',
    'home.report_issue': 'اضغط لإرفاق مشكلتك',
    'home.report_issue_en': 'Report an issue!',
    'home.quick_report': 'Quick Report',
    'home.quick_report_sub': 'اختر نوع المشكلة',
    'home.explore_map': 'Explore on map',
    'home.explore_map_sub': 'See community reports near you',
    'home.explore_map_count': 'reports added in total',
    'home.recent_reports': 'Recent Reports',
    'home.view_all': 'View all',
    'home.no_reports_yet': 'No reports yet',
    'home.submit_first': 'Submit your first one!',
    'home.submit_first_btn': 'Submit a Report',
    'home.delete_swipe_label': 'Delete',
    'home.delete_swipe_hint': 'Swipe left to delete this report',
    'home.delete_title': 'Delete Report?',
    'home.delete_body_prefix': 'Permanently delete "',
    'home.delete_body_suffix': '"? This cannot be undone.',
    'home.deleted_toast': 'Report deleted',
    'cat.all': 'All categories',
    'status.sent': 'Sent',
    'status.processing': 'Processing',
    'status.resolved': 'Resolved',
    'status.all': 'All',
    'status.all_status': 'All status',
    'my.title': 'My Reports',
    'my.search_hint': 'Search by title, address, or ID',
    'my.no_matches': 'No matches',
    'my.try_other': 'Try a different search or filter',
    'my.sort_title': 'Sort by',
    'my.sort_newest': 'Newest first',
    'my.sort_oldest': 'Oldest first',
    'submit.title': 'Submit Report',
    'submit.photo': 'PHOTO',
    'submit.tap_photo': 'Tap to add photo',
    'submit.photo_hint': 'Any image format · up to 10MB',
    'submit.problem_type': 'PROBLEM TYPE',
    'submit.description': 'DESCRIPTION',
    'submit.description_hint': 'Describe the problem in detail…',
    'submit.location': 'LOCATION',
    'submit.address_hint': 'Al-Yamouk Street, Block 5',
    'submit.pick_on_map': 'Pick on map',
    'submit.pick_on_map_hint': 'Tap to choose the spot on the map',
    'submit.location_selected': 'Location selected',
    'submit.use_my_location': 'Use my current location',
    'submit.submit_button': 'Submit Report',
    'submit.success': 'Report submitted successfully',
    'submit.desc_min': 'Please add a longer description (5+ chars)',
    'submit.nearby_title': 'Similar report nearby',
    'submit.nearby_hint': 'This issue may already be reported. Tap to view.',
    'detail.title': 'Report Detail',
    'detail.status_submitted': 'Submitted',
    'detail.status_processing': 'Processing',
    'detail.status_resolved': 'Resolved',
    'detail.in_review': 'In review',
    'detail.eta_prefix': 'ETA ',
    'detail.done': 'Done',
    'detail.pending': 'Pending',
    'detail.report_info': 'REPORT INFO',
    'detail.category': 'Category',
    'detail.submitted_on': 'Submitted',
    'detail.last_updated': 'Last updated',
    'detail.assigned_to': 'Assigned to',
    'detail.est_fix': 'Est. Fix',
    'detail.reporter_contact': 'REPORTER CONTACT',
    'detail.user_description': 'USER DESCRIPTION',
    'detail.follow': 'Follow',
    'detail.following': 'Following',
    'detail.location_pending': 'Location not provided',
    'map.title': 'Reports Map',
    'map.locate': 'Show my location',
    'map.loading': 'Loading reports…',
    'map.no_match': 'No reports match your filters',
    'map.open_details': 'Open Details',
    'map.unnamed_location': 'Unnamed location',
    'profile.title': 'Profile',
    'profile.sent_reports': 'Sent Reports',
    'profile.solved_reports': 'Solved Reports',
    'profile.change_password': 'Change Password',
    'profile.notifications': 'Notifications',
    'profile.privacy_legal': 'Privacy & Legal',
    'profile.log_out': 'Log Out',
    'profile.logout_title': 'Log Out',
    'profile.logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
    'profile.edit_profile': 'Edit Profile',
    'profile.edit_subtitle': 'Update your personal information',
    'profile.save_changes': 'Save Changes',
    'profile.profile_updated': 'Profile updated',
    'profile.password_updated': 'Password updated',
    'profile.current_password': 'Current password',
    'profile.new_password': 'New password',
    'profile.confirm_new': 'Confirm new password',
    'profile.first_name': 'First name',
    'profile.last_name': 'Last name',
    'profile.phone': 'Phone',
    'profile.language': 'Language',
    'profile.language_title': 'Language',
    'profile.language_en': 'English',
    'profile.language_ar': 'العربية',
    'profile.err_current_required': 'Enter your current password',
    'profile.err_new_short': 'New password must be at least 6 characters',
    'profile.err_mismatch': 'New passwords do not match',
    'profile.err_same': 'New password must be different from current',
    'profile.err_names_required': 'First name and last name are required',
    'notif.title': 'Notifications',
    'notif.empty': 'No notifications yet',
    'notif.empty_sub': "You'll see report status updates here",
    'notif.mark_all': 'Mark all read',
    'notif.just_now': 'just now',
  };

  static const _ar = <String, String>{
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.close': 'إغلاق',
    'common.share': 'مشاركة',
    'common.update': 'تحديث',
    'common.retry': 'إعادة المحاولة',
    'common.undo': 'تراجع',
    'common.required': 'مطلوب',
    'common.toggle_password': 'إظهار أو إخفاء كلمة المرور',
    'common.error': 'خطأ',
    'common.loading': 'جارٍ التحميل…',
    'nav.home': 'الرئيسية',
    'nav.my_reports': 'تقاريري',
    'nav.profile': 'الملف الشخصي',
    'nav.report': 'بلّغ',
    'app.exit_title': 'مغادرة التطبيق',
    'app.exit_message': 'هل أنت متأكد أنك تريد المغادرة؟',
    'app.yes': 'نعم',
    'app.no': 'لا',
    'login.welcome_back': 'مرحباً بعودتك',
    'login.subtitle': 'سجّل الدخول للمتابعة',
    'login.identifier_label': 'رقم الهاتف',
    'login.identifier_hint': 'يبدأ بـ 077 أو 078 أو 079',
    'login.password_label': 'كلمة المرور',
    'login.password_hint': 'كلمة المرور الخاصة بك',
    'login.sign_in': 'تسجيل الدخول',
    'login.no_account': 'ليس لديك حساب؟ ',
    'login.sign_up_link': 'إنشاء حساب',
    'login.invalid_phone': 'يجب أن يبدأ رقم الهاتف بـ 077 أو 078 أو 079',
    'login.enter_phone': 'أدخل رقم هاتفك',
    'login.phone_not_registered': 'رقم الهاتف غير صحيح!',
    'login.wrong_password': 'كلمة المرور غير صحيحة',
    'ar.phone_number': 'رقم الهاتف',
    'ar.password': 'كلمة المرور',
    'ar.first_name': 'الاسم الأول',
    'ar.last_name': 'اسم العائلة',
    'ar.photo': 'صورة',
    'ar.problem_type': 'نوع المشكلة',
    'ar.description': 'الوصف',
    'ar.location': 'الموقع',
    'register.create_account': 'إنشاء حساب',
    'register.subtitle': 'انضم إلى الآلاف في الإبلاغ عن المشكلات المجتمعية',
    'register.phone_label': 'رقم الهاتف',
    'register.phone_hint': 'يبدأ بـ 077 أو 078 أو 079',
    'register.first_name': 'الاسم الأول',
    'register.first_hint': 'الأول',
    'register.last_name': 'اسم العائلة',
    'register.last_hint': 'الأخير',
    'register.password': 'كلمة المرور',
    'register.password_hint': 'أنشئ كلمة مرور',
    'register.password_min': '6 أحرف على الأقل',
    'register.sign_up': 'إنشاء حساب',
    'register.have_account': 'لديك حساب بالفعل؟ ',
    'register.sign_in_link': 'تسجيل الدخول',
    'home.welcome': 'مرحباً',
    'home.stat_total': 'الإجمالي',
    'home.stat_resolved': 'تم الحل',
    'home.stat_active': 'قيد المعالجة',
    'home.report_issue': 'اضغط لإرفاق مشكلتك',
    'home.report_issue_en': 'أبلغ عن مشكلة!',
    'home.quick_report': 'بلّغ بسرعة',
    'home.quick_report_sub': 'اختر نوع المشكلة',
    'home.explore_map': 'استكشف الخريطة',
    'home.explore_map_sub': 'شاهد تقارير المجتمع القريبة منك',
    'home.explore_map_count': 'تقريرًا أُضيف في المجمل',
    'home.recent_reports': 'أحدث التقارير',
    'home.view_all': 'عرض الكل',
    'home.no_reports_yet': 'لا توجد تقارير بعد',
    'home.submit_first': 'أرسل أول تقرير لك!',
    'home.submit_first_btn': 'أرسل تقريراً',
    'home.delete_swipe_label': 'حذف',
    'home.delete_swipe_hint': 'اسحب لليسار لحذف هذا التقرير',
    'home.delete_title': 'حذف التقرير؟',
    'home.delete_body_prefix': 'حذف نهائي لـ "',
    'home.delete_body_suffix': '"؟ لا يمكن التراجع عن هذا الإجراء.',
    'home.deleted_toast': 'تم حذف التقرير',
    'cat.all': 'جميع الفئات',
    'status.sent': 'أُرسل',
    'status.processing': 'قيد المعالجة',
    'status.resolved': 'تم الحل',
    'status.all': 'الكل',
    'status.all_status': 'جميع الحالات',
    'my.title': 'تقاريري',
    'my.search_hint': 'ابحث بالعنوان أو الموقع أو الرقم',
    'my.no_matches': 'لا توجد نتائج',
    'my.try_other': 'جرّب بحثاً أو فلتراً مختلفاً',
    'my.sort_title': 'ترتيب حسب',
    'my.sort_newest': 'الأحدث أولاً',
    'my.sort_oldest': 'الأقدم أولاً',
    'submit.title': 'أبلغ عن مشكلة',
    'submit.photo': 'الصورة',
    'submit.tap_photo': 'اضغط لإضافة صورة',
    'submit.photo_hint': 'أي صيغة صورة · حتى 10 ميجابايت',
    'submit.problem_type': 'نوع المشكلة',
    'submit.description': 'الوصف',
    'submit.description_hint': 'صِف المشكلة بالتفصيل…',
    'submit.location': 'الموقع',
    'submit.address_hint': 'شارع اليرموك، حي 5',
    'submit.pick_on_map': 'اختر من الخريطة',
    'submit.pick_on_map_hint': 'اضغط لاختيار الموقع على الخريطة',
    'submit.location_selected': 'تم اختيار الموقع',
    'submit.use_my_location': 'استخدم موقعي الحالي',
    'submit.submit_button': 'أرسل التقرير',
    'submit.success': 'تم إرسال التقرير بنجاح',
    'submit.desc_min': 'الرجاء إضافة وصف أطول (5 أحرف فأكثر)',
    'submit.nearby_title': 'يوجد تقرير مشابه قريب',
    'submit.nearby_hint': 'قد تكون هذه المشكلة مُبلّغاً عنها بالفعل. اضغط للعرض.',
    'detail.title': 'تفاصيل التقرير',
    'detail.status_submitted': 'أُرسل',
    'detail.status_processing': 'قيد المعالجة',
    'detail.status_resolved': 'تم الحل',
    'detail.in_review': 'قيد المراجعة',
    'detail.eta_prefix': 'الموعد المتوقع ',
    'detail.done': 'اكتمل',
    'detail.pending': 'معلّق',
    'detail.report_info': 'معلومات التقرير',
    'detail.category': 'الفئة',
    'detail.submitted_on': 'تاريخ الإرسال',
    'detail.last_updated': 'آخر تحديث',
    'detail.assigned_to': 'مُسند إلى',
    'detail.est_fix': 'الإصلاح المتوقع',
    'detail.reporter_contact': 'معلومات المبلّغ',
    'detail.user_description': 'وصف المستخدم',
    'detail.follow': 'متابعة',
    'detail.following': 'تتابع الآن',
    'detail.location_pending': 'الموقع غير محدد',
    'map.title': 'خريطة التقارير',
    'map.locate': 'إظهار موقعي',
    'map.loading': 'جارٍ تحميل التقارير…',
    'map.no_match': 'لا توجد تقارير مطابقة للفلاتر',
    'map.open_details': 'عرض التفاصيل',
    'map.unnamed_location': 'موقع غير محدد',
    'profile.title': 'الملف الشخصي',
    'profile.sent_reports': 'تقارير مُرسلة',
    'profile.solved_reports': 'تقارير محلولة',
    'profile.change_password': 'تغيير كلمة المرور',
    'profile.notifications': 'الإشعارات',
    'profile.privacy_legal': 'الخصوصية والقانون',
    'profile.log_out': 'تسجيل الخروج',
    'profile.logout_title': 'تسجيل الخروج',
    'profile.logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
    'profile.edit_profile': 'تعديل الملف الشخصي',
    'profile.edit_subtitle': 'حدّث معلوماتك الشخصية',
    'profile.save_changes': 'حفظ التغييرات',
    'profile.profile_updated': 'تم تحديث الملف الشخصي',
    'profile.password_updated': 'تم تحديث كلمة المرور',
    'profile.current_password': 'كلمة المرور الحالية',
    'profile.new_password': 'كلمة المرور الجديدة',
    'profile.confirm_new': 'تأكيد كلمة المرور الجديدة',
    'profile.first_name': 'الاسم الأول',
    'profile.last_name': 'اسم العائلة',
    'profile.phone': 'رقم الهاتف',
    'profile.language': 'اللغة',
    'profile.language_title': 'اللغة',
    'profile.language_en': 'English',
    'profile.language_ar': 'العربية',
    'profile.err_current_required': 'أدخل كلمة المرور الحالية',
    'profile.err_new_short': 'يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل',
    'profile.err_mismatch': 'كلمتا المرور غير متطابقتين',
    'profile.err_same': 'يجب أن تختلف كلمة المرور الجديدة عن الحالية',
    'profile.err_names_required': 'الاسم الأول واسم العائلة مطلوبان',
    'notif.title': 'الإشعارات',
    'notif.empty': 'لا توجد إشعارات بعد',
    'notif.empty_sub': 'ستظهر هنا تحديثات حالة التقارير',
    'notif.mark_all': 'تحديد الكل كمقروء',
    'notif.just_now': 'الآن',
  };

  // Resolves a key against the active locale. Watches LocaleState so any
  // widget that renders a translated string rebuilds on language switch.
  static String of(BuildContext context, String key) {
    final isAr = context.watch<LocaleState>().isArabic;
    final map = isAr ? _ar : _en;
    return map[key] ?? _en[key] ?? key;
  }
}

extension AppStringsX on BuildContext {
  String t(String key) => AppStrings.of(this, key);
}
